# @package etl

target_crs: EPSG:3161
target_resolution: 20.0
reference_raster: ''
resampling_continuous: bilinear
resampling_categorical: nearest
features: {}
labels: {}
output_dpath: ${execution.exp_root}/harmonized
